FROM node:20-alpine AS base

WORKDIR /app

COPY package.json ./
RUN npm i

COPY . .


FROM base AS dev

EXPOSE 3000
CMD ["npm", "run", "dev"]


FROM base AS prod

RUN npm install -g serve
COPY --from=builder /app/dist /app/dist
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
