FROM node:20-alpine AS base

WORKDIR /app

COPY package.json ./
RUN npm i

COPY . .


FROM base AS dev

EXPOSE 3000
CMD ["npm", "run", "dev"]


FROM base AS prod

RUN npm run build
EXPOSE 3000
CMD ["npx", "serve", "-s", "dist", "-l", "3000"]
